using ApiProject;
using ApiProjectNestedClassLibrary;
using Microsoft.Extensions.Options;

var builder = WebApplication.CreateBuilder(args);

builder.AddAppSettingsFromApiProject();
builder.Services.AddAppSettingsFromApiProjectNestedClassLibrary(builder.Configuration);

// Add services to the container.

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseHttpsRedirection();

app.MapGet("/test", (
	IOptions<DataAnnotationWithNoValidationOrSectionNameSettings> dataAnnotationWithNoValidationOrSectionNameSettings,
	IOptions<DataAnnotationWithNoValidationButWithSectionNameSettings> dataAnnotationWithNoValidationButWithSectionNameSettings,
	IOptions<DataAnnotationWithValidationButNoSectionNameSettings> dataAnnotationWithValidationButNoSectionNameSettings,
	IOptions<DataAnnotationWithValidationAndSectionNameSettings> dataAnnotationWithValidationAndSectionNameSettings,
	IOptions<DataAnnotationNestedSettings> dataAnnotationNestedSettings,

	IOptions<FluentValidationWithNoValidationOrSectionNameSettings> fluentValidationWithNoValidationOrSectionNameSettings,
	IOptions<FluentValidationWithNoValidationButWithSectionNameSettings> fluentValidationWithNoValidationButWithSectionNameSettings,
	IOptions<FluentValidationWithValidationButNoSectionNameSettings> fluentValidationWithValidationButNoSectionNameSettings,
	IOptions<FluentValidationWithValidationAndSectionNameSettings> fluentValidationWithValidationAndSectionNameSettings,
	IOptions<FluentValidationNestedSettings> fluentValidationNestedSettings,
	IOptions<NestedClassLibraryAppSetting> nestedClassLibraryAppSetting) =>
{
	return $"""
	DataAnnotation
	Text from DataAnnotationWithNoValidationOrSectionNameSettings: {dataAnnotationWithNoValidationOrSectionNameSettings.Value.Text}
	Text from DataAnnotationWithNoValidationButWithSectionNameSettings: {dataAnnotationWithNoValidationButWithSectionNameSettings.Value.Text}
	Text from DataAnnotationWithValidationButNoSectionNameSettings: {dataAnnotationWithValidationButNoSectionNameSettings.Value.Text}
	Text from DataAnnotationWithValidationAndSectionNameSettings: {dataAnnotationWithValidationAndSectionNameSettings.Value.Text}
	Text from DataAnnotationNestedSettings: {dataAnnotationNestedSettings.Value.Text}
		
	FluentValidation
	Text from FluentValidationWithNoValidationOrSectionNameSettings: {fluentValidationWithNoValidationOrSectionNameSettings.Value.Text}
	Text from FluentValidationWithNoValidationButWithSectionNameSettings: {fluentValidationWithNoValidationButWithSectionNameSettings.Value.Text}
	Text from FluentValidationWithValidationButNoSectionNameSettings: {fluentValidationWithValidationButNoSectionNameSettings.Value.Text}
	Text from FluentValidationWithValidationAndSectionNameSettings: {fluentValidationWithValidationAndSectionNameSettings.Value.Text}
	Text from FluentValidationNestedSettings: {fluentValidationNestedSettings.Value.Text}
		
	Class Library
	Text from NestedClassLibraryAppSetting: {nestedClassLibraryAppSetting.Value.Test}
	""";
});


await app.RunAsync();
